### ISSUE TITLE
Automatically build new version and publish release on GitHub

### ISSUE THREAD

**Issue by mr-manuel** [ddeml/LoxStatEdit#4]
Hello,

I really like your project and want to help to make things a bit easier and clearer, since it‘s difficult to find the latest binary version of this project.

It‘s possible to automatically build the project and create a release with Github Actions, if you push a version tag, a commit or PR for example.

Here an example: https://github.com/mr-manuel/Loxone_LoxStatEdit/actions

What do you think about it?

**Comment by ddeml** [comment]
Hi Manuel,

first of all, I am very sorry for the late response.

I am afraid that I do not have the time to maintain this project in a serious manner. I hacked it down eons ago and just put it online so that anyone else may save some time and effort.

I can certainly make you a collaborator. I also found the “transfer ownership” feature if that would make sense for you?

Thank you very much and best regards - Richard

From: Manuel ***@***.***>
Sent: Freitag, 22. September 2023 07:36
To: ddeml/LoxStatEdit ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ddeml/LoxStatEdit] Automatically build new version and publish release on GitHub (Issue #4)


Hello,

I really like your project and want to help to make things a bit easier and clearer, since it‘s difficult to find the latest binary version of this project.

It‘s possible to automatically build the project and create a release with Github Actions, if you push a version tag, a commit or PR for example.

Here an example: https://github.com/mr-manuel/InfluxDBStudio/blob/master/.github/workflows/dotnet-desktop-release.yml

What do you think about it?

**Comment by mr-manuel** [comment]
> I am afraid that I do not have the time to maintain this project in a serious manner. I hacked it down eons ago and just put it online so that anyone else may save some time and effort.

Thank you for sharing the source code!

> I can certainly make you a collaborator. I also found the “transfer ownership” feature if that would make sense for you?

Collaborator is good, It's not needed to transfer ownership. You put the most effort into this program and I don't want to take that into my account.

In my fork you can see that I added a readme and a sponsor link. Before opening a PR to this repository I would also add a donation link for you. Do you want that? If yes please send me the link.

Thank you again for this great work.
